# Spectrum-Based Fault Localization comparison visualization
#
# This script reads the real evaluation metrics generated by main_pipeline.py
# and compares the baseline HDD+SBFL pipeline against the weighted HDD+WDD
# pipeline. It does not use any synthetic placeholder comparison data.

library(ggplot2)

metrics_path <- "sbfl_comparison_metrics.csv"
if (!file.exists(metrics_path)) {
  stop("Missing ", metrics_path, ". Run `python main_pipeline.py` first to generate the comparison metrics.")
}

comparison <- read.csv(metrics_path, stringsAsFactors = FALSE)

# Normalize factor levels so plots appear in a stable, logical order.
comparison$Method <- factor(comparison$Method, levels = c("Baseline", "Weighted"))
comparison$Formula <- factor(comparison$Formula, levels = c("Ochiai", "Tarantula", "Jaccard", "DStar"))
comparison$Program <- factor(comparison$Program)

# Convert numeric columns explicitly in case CSV parsing is loose.
comparison$Exam_Score <- as.numeric(comparison$Exam_Score)
comparison$First_Fault_Rank <- as.numeric(comparison$First_Fault_Rank)
comparison$Top_1 <- as.numeric(comparison$Top_1)
comparison$Top_3 <- as.numeric(comparison$Top_3)
comparison$Top_5 <- as.numeric(comparison$Top_5)
comparison$Top_10 <- as.numeric(comparison$Top_10)

# Long-form data for the binary Top-N metrics.
top_long <- rbind(
  data.frame(Program = comparison$Program, Formula = comparison$Formula, Method = comparison$Method, Metric = "Top@1", Value = comparison$Top_1),
  data.frame(Program = comparison$Program, Formula = comparison$Formula, Method = comparison$Method, Metric = "Top@3", Value = comparison$Top_3),
  data.frame(Program = comparison$Program, Formula = comparison$Formula, Method = comparison$Method, Metric = "Top@5", Value = comparison$Top_5),
  data.frame(Program = comparison$Program, Formula = comparison$Formula, Method = comparison$Method, Metric = "Top@10", Value = comparison$Top_10)
)
top_long$Metric <- factor(top_long$Metric, levels = c("Top@1", "Top@3", "Top@5", "Top@10"))

# Long-form data for EXAM score and first faulty line rank.
rank_long <- rbind(
  data.frame(Program = comparison$Program, Formula = comparison$Formula, Method = comparison$Method, Metric = "EXAM Score", Value = comparison$Exam_Score),
  data.frame(Program = comparison$Program, Formula = comparison$Formula, Method = comparison$Method, Metric = "First Fault Rank", Value = comparison$First_Fault_Rank)
)
rank_long$Metric <- factor(rank_long$Metric, levels = c("EXAM Score", "First Fault Rank"))

# Figure 1: rank-based metrics (EXAM score and first faulty line rank)
figure1 <- ggplot(rank_long, aes(x = Method, y = Value, fill = Method)) +
  geom_col(width = 0.68, colour = "grey25", position = position_dodge(width = 0.75)) +
  facet_grid(Metric ~ Formula, scales = "free_y") +
  scale_y_continuous(breaks = function(limits) pretty(limits, n = 5)) +
  labs(
    title = "Baseline vs Weighted HDD-LOC: Rank-Based Evaluation Metrics",
    x = NULL,
    y = "Metric Value"
  ) +
  theme_bw() +
  theme(
    axis.text.x = element_text(angle = 35, hjust = 1, vjust = 1),
    legend.position = "top",
    strip.background = element_rect(fill = "grey92", colour = "grey60"),
    strip.text = element_text(face = "bold")
  )

print(figure1)

# Figure 2: Top-N hit metrics
figure2 <- ggplot(top_long, aes(x = Metric, y = Value, fill = Method)) +
  geom_col(width = 0.72, colour = "grey25", position = position_dodge(width = 0.8)) +
  facet_grid(Formula ~ .) +
  scale_y_continuous(
    limits = c(0, 1),
    breaks = seq(0, 1, by = 0.25),
    labels = function(x) paste0(round(100 * x), "%")
  ) +
  labs(
    title = "Baseline vs Weighted HDD-LOC: Top-N Inspection Metrics",
    x = "Inspection Metric",
    y = "Hit Rate"
  ) +
  theme_bw() +
  theme(
    axis.text.x = element_text(angle = 35, hjust = 1, vjust = 1),
    legend.position = "none",
    strip.background = element_rect(fill = "grey92", colour = "grey60"),
    strip.text = element_text(face = "bold")
  )

print(figure2)
